[package]
name = "lang-turtle"
version = "0.1.0"    # the current version, obeying semver
edition = "2021"     # the edition, will have no effect on a resolver used in the workspace
authors = ["Arthur Vercruysse <arthur.vercruysse@outlook.com>"]

[dependencies]
enum-methods.workspace = true
sophia_api.workspace = true
sophia_iri.workspace = true
serde_json.workspace = true
tracing.workspace = true
tokio.workspace = true
chumsky.workspace = true
ropey.workspace = true
lsp-types.workspace = true
futures.workspace = true
tower-lsp.workspace = true
hashbrown.workspace = true
async-trait.workspace = true

lsp-core = {path = "../core/"}
