name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native:
    name: Build and Test (Native)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build workspace
        run: cargo build --all-targets --workspace --exclude lsp-web

      - name: Run tests
        run: cargo test --workspace --exclude lsp-web

  build-web:
    name: Build (WASM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust with wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Build WASM
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build -p lsp-web --target wasm32-unknown-unknown 

  doc:
    name: Generate Docs
    runs-on: ubuntu-latest
    needs: build-native

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Documentation
        run: cargo doc --workspace

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: docs
          publish_dir: target/doc

