name: Main

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"  # Triggers on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allows manual runs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
            LICENSE
            
