name: Release LSP

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"  # Triggers on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allows manual runs

jobs:
  build:
    name: Build Native LSP Binary
    runs-on: ${{ matrix.platform }}
    
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build LSP Binary
        run: cargo build --release -p lsp-bin

      - name: Rename binary for release
        shell: bash
        run: |
          mkdir -p release
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            cp target/release/lsp-bin release/lsp_bin-linux-x86_64
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            cp target/release/lsp-bin release/lsp_bin-macos-x86_64
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            cp target/release/lsp-bin.exe release/lsp_bin-windows-x86_64.exe
          fi

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: lsp_bin-${{ runner.os }}-x86_64
          path: release/*
  
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: release

      - name: List downloaded files
        run: ls -R release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*
          body: "🚀 New release of LSP! Includes native binaries for Linux, macOS and Windows."

